In [ ]:
#Lakshya Sonawane PRN:25070123068
#Title : Study of NumPy library in python

In [ ]:
#Why NumPy?
#Faster than lists
# Used for numerical computation
# Base for Pandas


In [7]:
#Declaration of Numpy
import numpy as np
a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)


[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
#Dimension of Array
print(a.ndim)
print(b.ndim)
print(a.size,b.size)
print(a.shape)
print(b.shape)
print(a.dtype)
print(b.dtype)


1
2
7 9
(7,)
(3, 3)
int64
int64


In [16]:
#In-Built functions using Numpy
np.zeros((2,3))



array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [21]:
np.linspace(0,1,4)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[  6  15  25  35  45  55 505]


In [23]:
a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)
print(b * 2)
print(a + 5)
#print(a)
#print(b)


[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[  6  15  25  35  45  55 505]


In [26]:
np.mean(a)

np.float64(93.0)

In [27]:
np.median(a)

np.float64(30.0)

In [28]:
np.max(a)

np.int64(500)

In [29]:
np.min(a)

np.int64(1)

In [30]:
np.sum(a)

np.int64(651)

np.int64(651)